// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjYOyhsfyY51mWWQfUzh0yc7IKxZ-bjf4',
    appId: '1:864408989412:web:48c1f1350a1085fac3c6f1',
    messagingSenderId: '864408989412',
    projectId: 'student-app-dd0b1',
    authDomain: 'student-app-dd0b1.firebaseapp.com',
    storageBucket: 'student-app-dd0b1.firebasestorage.app',
    measurementId: 'G-Q2R69FLQYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_rMukKlOKcS0aYEH6aii9_4vvYnpt0yU',
    appId: '1:864408989412:android:6be8cacaa821b2a6c3c6f1',
    messagingSenderId: '864408989412',
    projectId: 'student-app-dd0b1',
    storageBucket: 'student-app-dd0b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq9Q1c7PhYOAzZkXOaqvtawkQWAuiNwHk',
    appId: '1:864408989412:ios:3bcf182bff446028c3c6f1',
    messagingSenderId: '864408989412',
    projectId: 'student-app-dd0b1',
    storageBucket: 'student-app-dd0b1.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectroryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq9Q1c7PhYOAzZkXOaqvtawkQWAuiNwHk',
    appId: '1:864408989412:ios:3bcf182bff446028c3c6f1',
    messagingSenderId: '864408989412',
    projectId: 'student-app-dd0b1',
    storageBucket: 'student-app-dd0b1.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectroryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjYOyhsfyY51mWWQfUzh0yc7IKxZ-bjf4',
    appId: '1:864408989412:web:cbc6f591a08fd593c3c6f1',
    messagingSenderId: '864408989412',
    projectId: 'student-app-dd0b1',
    authDomain: 'student-app-dd0b1.firebaseapp.com',
    storageBucket: 'student-app-dd0b1.firebasestorage.app',
    measurementId: 'G-51CDWNXZVP',
  );
}
